import os
import subprocess
import sys

import pandas as pd
import streamlit as st

from dotenv import load_dotenv
from langchain_groq import ChatGroq
from langchain.agents import create_agent
from langchain_core.tools import tool


load_dotenv()


UPLOAD_FOLDER = "uploads"
SCRIPT_FOLDER = "python_script"

os.makedirs(UPLOAD_FOLDER, exist_ok=True)
os.makedirs(SCRIPT_FOLDER, exist_ok=True)


@tool
def run_python_analysis(
    python_code: list[str],
    data_file_path: str
) -> str:
    """Save and execute Python code generated by the LLM."""

    script_path = os.path.join(
        SCRIPT_FOLDER,
        "analysis_script.py"
    )

    try:

        code = "\n".join(python_code)

        with open(
            script_path,
            "w",
            encoding="utf-8"
        ) as f:
            f.write(code)

        result = subprocess.run(
            [
                sys.executable,
                script_path,
                data_file_path
            ],
            capture_output=True,
            text=True,
            timeout=120
        )

        if result.returncode != 0:

            return (
                "PYTHON SCRIPT FAILED\n\n"
                "STDOUT:\n"
                f"{result.stdout}\n\n"
                "STDERR:\n"
                f"{result.stderr}"
            )

        return (
            "PYTHON SCRIPT EXECUTED SUCCESSFULLY\n\n"
            "OUTPUT:\n"
            f"{result.stdout}"
        )

    except subprocess.TimeoutExpired:

        return (
            "ERROR: Python script exceeded "
            "the 120 second execution limit."
        )

    except Exception as e:

        return (
            f"ERROR EXECUTING PYTHON SCRIPT: {str(e)}"
        )


SYSTEM_PROMPT = """
You are a Data Analyst AI Agent responsible for performing
data validation and exploratory data analysis on an Excel file.

Your job is to:

1. Inspect the actual dataset.
2. Understand its structure.
3. Decide which validations and analyses are relevant.
4. Generate Python code.
5. Execute the Python code using the run_python_analysis tool.
6. Review the actual Python results.
7. Return a final consolidated analysis response.

STEP 1 — INSPECT THE DATASET

Inspect the provided Excel file.

Read the first 4 rows to understand:

- column names
- sample values
- apparent data types
- possible meaning of columns

The provided Excel file contains only the sheet
that the user selected.

Do not ask the user for the sheet name.


STEP 2 — DECIDE THE ANALYSIS

Understand the dataset structure.

Dynamically decide which validations and exploratory
analyses are relevant based on the actual dataset.

Do not use a fixed validation list.

Do not assume specific column names.

Do not assume every dataset requires the same validations.

Choose validations based on the actual dataset.

Choose numerical analysis for relevant numerical columns.

Choose categorical analysis for relevant categorical columns.

Choose date analysis for relevant date/datetime columns.


STEP 3 — GENERATE PYTHON

Generate executable Python code using pandas.

The Python script must:

- Load the Excel file.
- Use sys.argv[1] as the file path.
- Perform the required validations.
- Perform the required exploratory analysis.
- Calculate all data-dependent values using Python.
- Print clear and structured results.

Use:

import sys

file_path = sys.argv[1]

Do NOT hardcode the Excel file path.


STEP 4 — EXECUTE PYTHON

Use the run_python_analysis tool.

IMPORTANT:

The python_code argument must be a LIST of Python code lines.

Each item must contain one Python line.

Example:

[
    "import sys",
    "import pandas as pd",
    "file_path = sys.argv[1]",
    "df = pd.read_excel(file_path)"
]

Do not use markdown code fences.

Do not include explanations inside python_code.

data_file_path must be the exact file path provided.

The generated script is saved as:

python_script/analysis_script.py


STEP 5 — REVIEW PYTHON RESULTS

Review the output returned by run_python_analysis.

Python performs the actual calculations.

Do not invent values.

Do not estimate values.

Do not calculate data-dependent values yourself.

If Python fails:

1. Inspect the error.
2. Correct the Python code.
3. Call run_python_analysis again.
4. Review the corrected result.


STEP 6 — FINAL RESPONSE

After Python executes successfully, return a consolidated
Data Analyst response.

The response must contain the actual values obtained
from Python.

Present the final response in a clear,
user-friendly TABLE FORMAT.

Use separate tables for the following sections
when applicable:

1. Dataset Overview

Columns:
- Metric
- Value

Include:
- Total Rows
- Total Columns


2. Column Details

Columns:
- Column Name
- Data Type
- null count
- null %

Use simple data types such as:
- string
- integer
- float
- boolean
- datetime

Do not use pandas dtype names such as:
- object
- int64
- float64
- datetime64[ns]


3. Data Validations

Columns:
- Test Name
- Test Status
- Fail Count
- Fail Percentage


4. Numerical Statistics

Columns:
- Column
- Mean
- Median
- Mode
- Min
- Max
- Q1
- Q3
- Standard Deviation


5. Categorical Statistics

Columns:
- Column
- Unique Count
- Most frequest Value and it's
- Share Percentage


6. Date Statistics

Columns:
- Column
- Minimum Date
- Maximum Date
- Missing Count


7. Key Findings

Columns:
- Finding
- Severity


IMPORTANT FINAL OUTPUT RULES:

- Make the tables easy for a non-technical user to understand.
- Include all relevant data returned by Python.
- Do not omit available results.
- Do not invent values.
- Do not estimate values.
- Do not calculate new values yourself.
- Do not return Python code.
- Do not only describe what was done.
- Return the actual analysis results in tables.
"""


llm = ChatGroq(
    model="openai/gpt-oss-120b",
    temperature=0
)


agent = create_agent(
    model=llm,
    tools=[run_python_analysis],
    system_prompt=SYSTEM_PROMPT
)


st.title("📊 Let's Do EDA")

st.subheader("Please Upload Your Data 👩🏻")

st.markdown(
    "Please ensure it's an Excel file."
)


uploaded_file = st.file_uploader(
    "Upload Excel File",
    type=["xlsx"]
)


if uploaded_file:

    excel_file = pd.ExcelFile(uploaded_file)

    sheet_names = excel_file.sheet_names

    st.info(
        f"📑 This Excel file contains "
        f"{len(sheet_names)} sheet(s)."
    )

    selected_sheet = st.selectbox(
        "Select the sheet you want to analyze:",
        options=["-- Select a sheet --"] + sheet_names,
        index=0
    )

    if selected_sheet == "-- Select a sheet --":

        st.warning(
            "Please select a sheet to continue."
        )

    else:

        df = pd.read_excel(
            uploaded_file,
            sheet_name=selected_sheet
        )

        safe_sheet_name = (
            selected_sheet
            .replace(" ", "_")
            .replace("/", "_")
            .replace("\\", "_")
        )

        selected_file_path = os.path.join(
            UPLOAD_FOLDER,
            f"{safe_sheet_name}.xlsx"
        )

        df.to_excel(
            selected_file_path,
            index=False
        )

        st.success(
            f"✅ You selected: **{selected_sheet}**"
        )

        st.subheader("👀 Data Preview")

        st.dataframe(
            df.head(5),
            use_container_width=True
        )

        if st.button(
            "🚀 Analyze Dataset",
            type="primary"
        ):

            with st.spinner(
                "Analyzing your dataset..."
            ):

                try:

                    result = agent.invoke(
                        {
                            "messages": [
                                {
                                    "role": "user",
                                    "content": f"""
Analyze this Excel file:

{selected_file_path}
"""
                                }
                            ]
                        }
                    )

                    messages = result["messages"]

                    agent_response = messages[-1].content

                    if isinstance(agent_response, list):

                        agent_response = "\n".join(
                            str(item)
                            for item in agent_response
                        )

                    st.subheader("📊 Analysis Result")

                    st.write(agent_response)

                except Exception as e:

                    st.error(
                        f"Error during analysis: {str(e)}"
                    )